version: "3.1"

services:
  iot-temp-service:
    image: avegao/iot-temp-service:local
    container_name: iot-temp-service
    command: --debug --iot_arduino_server_addr=iot-arduino-temp-service:50000
    build:
      dockerfile: ./Dockerfile
      context: .
    networks:
      - iot-temp
      - iot-arduino-temp
    ports:
       - "50000:50000"
    environment:
      PGSQL_HOST: "192.168.1.177"
      PGSQL_USERNAME: "iot_temp"
      PGSQL_PASSWORD: "C7fJafnH6bQ7Cnmd"
      PGSQL_DATABASE: "iot"
    depends_on:
      - iot-arduino-temp-service

  iot-arduino-temp-service:
     image: avegao/iot-arduino-temp-service:local
     container_name: iot-arduino-temp-service
     command: --debug
     networks:
       - iot-arduino-temp

networks:
  iot-temp:
  iot-arduino-temp:
#    external:
#      name: iotarduino_iot-arduino-temp