version: "3.1"

services:
  iot-go:
    image: avegao/iot-temp-service:local
    container_name: iot_temp_service
    command: --debug
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
       - "50000:50000"

#  iot-mysql:
#    image: mariadb:10.1.23
#    container_name: iot_mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: "iot"
#      MYSQL_USER: "iot"
#      MYSQL_PASSWORD: "iot"
#      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
